# SPDX-License-Identifier: Apache-2.0
# File: deploy/istio/certs/letsencrypt-prod-clusterissuer.yaml
# Description:
#     Defines a cert-manager ClusterIssuer for Let's Encrypt (production).
#     Used for external TLS certificates (e.g., astradesk-tls in 50-cert-manager-certificate.yaml).
#     Configures ACME solver with HTTP-01 challenge for Istio Gateway.
# Author: Siergej Sobolewski
# Since: 2025-10-22

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: your-email@example.com  # Change to your email
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: istio