# SPDX-License-Identifier: Apache-2.0
# File: values.yaml
# Description:
#     Helm values for AstraDesk deployment.
#     Configures images, replicas, autoscaling (CPU 60%), and database connections.
# Author: Siergej Sobolewski
# Since: 2025-10-22

api:
  image:
    repository: docker.io/youruser/astradesk-api
    tag: latest
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 60
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"
  env:
    DATABASE_URL: postgresql://astradesk:astrapass@db:5432/astradesk
    NATS_URL: nats://nats:4222
    PACK_API_TOKEN: "your-jwt-token"

ticketAdapter:
  image:
    repository: docker.io/youruser/astradesk-ticket
    tag: latest
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1000m"
      memory: "1024Mi"
  env:
    MYSQL_URL_R2DBC: mysql://tickets:tickets@mysql:3306/tickets

admin:
  image:
    repository: docker.io/youruser/astradesk-admin
    tag: latest
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
  resources:
    requests:
      cpu: "300m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  env:
    API_URL: http://astradesk-api:8080

auditor:
  image:
    repository: docker.io/youruser/astradesk-auditor
    tag: latest
  replicas: 2
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 60
  resources:
    requests:
      cpu: "300m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
  env:
    NATS_URL: nats://nats:4222

database:
  postgres:
    host: ""
  mysql:
    host: ""
