# SPDX-License-Identifier: Apache-2.0
# File: packages/domain-finance/pyproject.toml
# Author: Siergej Sobolewski
# Since: 2025-10-27

[project]
name = "astradesk-domain-finance"
version = "0.3.0"
description = "Finance domain pack for AstraDesk — forecasting and ERP integration."
authors = [{ name = "Siergej Sobolewski", email = "s.sobolewski@hotmail.com" }]
license = "Apache-2.0"
requires-python = ">=3.14"

dependencies = [
  "astradesk-core",
  "prophet>=1.1,<2.0",
  "grpcio>=1.66,<2.0",
  "protobuf>=5.0",
]

[project.optional-dependencies]
dev = [
  "pytest>=8.3",
  "pytest-asyncio>=0.23",
  "respx>=0.20,<1.0",
  "grpcio-tools>=1.66,<2.0",
]

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = {find = {where = ["."]}}
