# SPDX-License-Identifier: Apache-2.0
# File: packages/domain-ops/pyproject.toml
# Author: Siergej Sobolewski
# Since: 2025-10-27

[project]
name = "astradesk-domain-ops"
version = "0.3.0"
description = "Operations (SRE/DevOps) domain pack for AstraDesk."
authors = [{ name = "Siergej Sobolewski", email = "s.sobolewski@hotmail.com" }]
license = "Apache-2.0"
requires-python = ">=3.14"

dependencies = [
  "astradesk-core",
  "kubernetes-asyncio>=20.0,<21.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3",
    "pytest-asyncio>=0.23",
]

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["proto*", "flows*", "agents*", "clients*", "policies*"]
