/* eslint-disable */
/* Auto-generated by scripts/openapi-generate.ts. Do not edit manually. */

export type SpecHttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';

export type SpecOperation = {
  tag: string;
  method: SpecHttpMethod;
  path: string;
};

export const specOperations: SpecOperation[] = [
  { tag: 'Agents', method: 'GET', path: '/agents' },
  { tag: 'Agents', method: 'POST', path: '/agents' },
  { tag: 'Agents', method: 'DELETE', path: '/agents/{id}' },
  { tag: 'Agents', method: 'GET', path: '/agents/{id}' },
  { tag: 'Agents', method: 'PUT', path: '/agents/{id}' },
  { tag: 'Agents', method: 'GET', path: '/agents/{id}/io' },
  { tag: 'Agents', method: 'GET', path: '/agents/{id}/metrics' },
  { tag: 'Agents', method: 'POST', path: '/agents/{id}:clone' },
  { tag: 'Agents', method: 'POST', path: '/agents/{id}:promote' },
  { tag: 'Agents', method: 'POST', path: '/agents/{id}:test' },
  { tag: 'Audit Trail', method: 'GET', path: '/audit' },
  { tag: 'Audit Trail', method: 'GET', path: '/audit/export' },
  { tag: 'Audit Trail', method: 'GET', path: '/audit/{id}' },
  { tag: 'Dashboard', method: 'GET', path: '/errors/recent' },
  { tag: 'Dashboard', method: 'GET', path: '/health' },
  { tag: 'Dashboard', method: 'GET', path: '/usage/llm' },
  { tag: 'Datasets', method: 'GET', path: '/datasets' },
  { tag: 'Datasets', method: 'POST', path: '/datasets' },
  { tag: 'Datasets', method: 'DELETE', path: '/datasets/{id}' },
  { tag: 'Datasets', method: 'GET', path: '/datasets/{id}' },
  { tag: 'Datasets', method: 'GET', path: '/datasets/{id}/embeddings' },
  { tag: 'Datasets', method: 'GET', path: '/datasets/{id}/schema' },
  { tag: 'Datasets', method: 'POST', path: '/datasets/{id}:reindex' },
  { tag: 'Domain Packs', method: 'GET', path: '/domain-packs' },
  { tag: 'Domain Packs', method: 'POST', path: '/domain-packs/{name}:install' },
  { tag: 'Domain Packs', method: 'POST', path: '/domain-packs/{name}:uninstall' },
  { tag: 'Flows', method: 'GET', path: '/flows' },
  { tag: 'Flows', method: 'POST', path: '/flows' },
  { tag: 'Flows', method: 'DELETE', path: '/flows/{id}' },
  { tag: 'Flows', method: 'GET', path: '/flows/{id}' },
  { tag: 'Flows', method: 'PUT', path: '/flows/{id}' },
  { tag: 'Flows', method: 'GET', path: '/flows/{id}/log' },
  { tag: 'Flows', method: 'POST', path: '/flows/{id}:dryrun' },
  { tag: 'Flows', method: 'POST', path: '/flows/{id}:validate' },
  { tag: 'Intent Graph', method: 'GET', path: '/intents/graph' },
  { tag: 'Jobs & Schedules', method: 'GET', path: '/dlq' },
  { tag: 'Jobs & Schedules', method: 'GET', path: '/jobs' },
  { tag: 'Jobs & Schedules', method: 'POST', path: '/jobs' },
  { tag: 'Jobs & Schedules', method: 'DELETE', path: '/jobs/{id}' },
  { tag: 'Jobs & Schedules', method: 'GET', path: '/jobs/{id}' },
  { tag: 'Jobs & Schedules', method: 'PUT', path: '/jobs/{id}' },
  { tag: 'Jobs & Schedules', method: 'POST', path: '/jobs/{id}:pause' },
  { tag: 'Jobs & Schedules', method: 'POST', path: '/jobs/{id}:resume' },
  { tag: 'Jobs & Schedules', method: 'POST', path: '/jobs/{id}:trigger' },
  { tag: 'Keys & Secrets', method: 'GET', path: '/secrets' },
  { tag: 'Keys & Secrets', method: 'POST', path: '/secrets' },
  { tag: 'Keys & Secrets', method: 'DELETE', path: '/secrets/{id}:disable' },
  { tag: 'Keys & Secrets', method: 'POST', path: '/secrets/{id}:rotate' },
  { tag: 'Policies', method: 'GET', path: '/policies' },
  { tag: 'Policies', method: 'POST', path: '/policies' },
  { tag: 'Policies', method: 'DELETE', path: '/policies/{id}' },
  { tag: 'Policies', method: 'GET', path: '/policies/{id}' },
  { tag: 'Policies', method: 'PUT', path: '/policies/{id}' },
  { tag: 'Policies', method: 'POST', path: '/policies/{id}:simulate' },
  { tag: 'Runs & Logs', method: 'GET', path: '/logs/export' },
  { tag: 'Runs & Logs', method: 'GET', path: '/runs' },
  { tag: 'Runs & Logs', method: 'GET', path: '/runs/stream' },
  { tag: 'Runs & Logs', method: 'GET', path: '/runs/{id}' },
  { tag: 'Settings', method: 'GET', path: '/settings/{group}' },
  { tag: 'Settings', method: 'PUT', path: '/settings/{group}' },
  { tag: 'Tools/Connectors', method: 'GET', path: '/connectors' },
  { tag: 'Tools/Connectors', method: 'POST', path: '/connectors' },
  { tag: 'Tools/Connectors', method: 'DELETE', path: '/connectors/{id}' },
  { tag: 'Tools/Connectors', method: 'GET', path: '/connectors/{id}' },
  { tag: 'Tools/Connectors', method: 'PUT', path: '/connectors/{id}' },
  { tag: 'Tools/Connectors', method: 'POST', path: '/connectors/{id}:probe' },
  { tag: 'Tools/Connectors', method: 'POST', path: '/connectors/{id}:test' },
  { tag: 'Users & Roles', method: 'GET', path: '/roles' },
  { tag: 'Users & Roles', method: 'GET', path: '/users' },
  { tag: 'Users & Roles', method: 'POST', path: '/users' },
  { tag: 'Users & Roles', method: 'DELETE', path: '/users/{id}' },
  { tag: 'Users & Roles', method: 'GET', path: '/users/{id}' },
  { tag: 'Users & Roles', method: 'PUT', path: '/users/{id}/role' },
  { tag: 'Users & Roles', method: 'POST', path: '/users/{id}:reset-mfa' },
];

const OPERATION_SET = new Set(specOperations.map((operation) => operationKey(operation)));

function operationKey(operation: SpecOperation): string {
  return `${operation.tag}|${operation.method}|${operation.path}`;
}

export function assertSpecOperation(tag: string, method: SpecHttpMethod, path: string): SpecOperation {
  const key = `${tag}|${method}|${path}`;
  if (!OPERATION_SET.has(key)) {
    throw new Error(`Operation not present in OpenAPI spec: ${method} ${path} (tag: ${tag})`);
  }
  return { tag, method, path };
}

