version: "3.9"
services:
  api:
    build: .
    env_file: .env
    ports: [ "8080:8080" ]
    depends_on: [ db, redis, nats, ticket-adapter ]
  ticket-adapter:
    build: services/ticket-adapter-java
    env_file: .env
    ports: [ "8081:8081" ]
    depends_on: [ mysql ]
  admin:
    build: services/admin-portal
    environment:
      NEXT_PUBLIC_API_URL: http://api:8080
    ports: [ "3000:3000" ]
    depends_on: [ api ]
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: astradesk
      POSTGRES_USER: astradesk
      POSTGRES_PASSWORD: astrapass
    ports: [ "5432:5432" ]
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: tickets
      MYSQL_USER: tickets
      MYSQL_PASSWORD: tickets
      MYSQL_ROOT_PASSWORD: root
    ports: [ "3306:3306" ]
  redis:
    image: redis:7
    ports: [ "6379:6379" ]
  nats:
    image: nats:2
    command: ["-js"]
    ports: [ "4222:4222","8222:8222" ]
