# ============================================================================
# AstraDesk — MkDocs Material configuration
# ============================================================================
site_name: AstraDesk Framework
site_description: "AstraDesk Enterprise AI Agents Framework — Technical Guide (v1.0)"
site_url: https://astradesk.vercel.app
repo_url: https://github.com/SSobol77/astradesk
repo_name: SSobol77/astradesk
copyright: "© 2025 AstraDesk"

docs_dir: docs

theme:
  name: material
  language: en
  logo: assets/astradesk-symbol.svg
  favicon: assets/astradesk-symbol.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - content.code.copy
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: false
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.emoji

plugins:
  - search
  - redoc
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - js/mermaid-init.js 

extra_css:
  - styles/mermaid-card.css

watch:
  - docs/js
  - docs/styles

nav:
  - Home: README.md
  - 1. Introduction: 01_introduction.md
  - 2. Architecture Overview: 02_architecture_overview.md
  - 3. Plan Phase: 03_plan_phase.md
  - 4. Build Phase: 04_build_phase.md
  - 5. Test & Optimize: 05_test_optimize.md
  - 6. Deploy Phase: 06_deploy_phase.md
  - 7. Monitor & Operate: 07_monitor_operate.md
  - 8. Security & Governance: 08_security_governance.md
  - 9. MCP Gateway & Domain Packs: 09_mcp_gateway_domain_packs.md
  - 10. Future Roadmap: 10_future_roadmap.md
  - Glossary: glossary.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SSobol77/astradesk
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/your-handle
      name: Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/your-company
      name: LinkedIn