# ============================================================================
# AstraDesk — MkDocs Material configuration
# ============================================================================
site_name: AstraDesk Framework
site_description: "AstraDesk Enterprise AI Agents Framework — Technical Guide (v1.0)"
site_url: https://astradesk.vercel.app
repo_url: https://github.com/SSobol77/astradesk
repo_name: SSobol77/astradesk
copyright: "© 2025 AstraDesk"

docs_dir: docs

theme:
  name: material
  language: en
  logo: assets/astradesk-symbol.svg
  favicon: assets/astradesk-symbol.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - content.code.copy
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
  palette:
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: false
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.emoji

plugins:
  - search
  - redoc
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js
  - js/mermaid-init.js 

extra_css:
  - styles/mermaid-card.css

watch:
  - docs/js
  - docs/styles

nav:
  - Home: README.md

  - Guides (EN):
      - Introduction: en/01_introduction.md
      - Architecture Overview: en/02_architecture_overview.md
      - Plan Phase: en/03_plan_phase.md
      - Build Phase: en/04_build_phase.md
      - Test & Optimize: en/05_test_optimize.md
      - Deploy Phase: en/06_deploy_phase.md
      - Monitor & Operate: en/07_monitor_operate.md
      - Security & Governance: en/08_security_governance.md
      - MCP Gateway & Domain Packs: en/09_mcp_gateway_domain_packs.md
      - Future Roadmap: en/10_future_roadmap.md
      - Glossary: en/glossary.md

  - Przewodniki (PL):
      - Wprowadzenie: pl/01_introduction.md
      - Przegląd Architektury: pl/02_architecture_overview.md
      - Faza Planowania: pl/03_plan_phase.md
      - Faza Budowy: pl/04_build_phase.md
      - Testy i Optymalizacja: pl/05_test_optimize.md
      - Faza Wdrożenia: pl/06_deploy_phase.md
      - Monitorowanie i Operacje: pl/07_monitor_operate.md
      - Bezpieczeństwo i Ład: pl/08_security_governance.md
      - MCP Gateway & Domain Packs: pl/09_mcp_gateway_domain_packs.md
      - Roadmapa: pl/10_future_roadmap.md
      - Słownik: pl/glossary.md

  - 指南 (ZH):
      - 介绍: zh/01_introduction.md
      - 架构概览: zh/02_architecture_overview.md
      - 规划阶段: zh/03_plan_phase.md
      - 构建阶段: zh/04_build_phase.md
      - 测试与优化: zh/05_test_optimize.md
      - 部署阶段: zh/06_deploy_phase.md
      - 监控与运维: zh/07_monitor_operate.md
      - 安全与治理: zh/08_security_governance.md
      - MCP 网关与领域包: zh/09_mcp_gateway_domain_packs.md
      - 路线图: zh/10_future_roadmap.md
      - 术语表: zh/glossary.md

  - API (Redoc):
      - Overview: api/index.md
      - Admin API v1.2.0 — Reference: !redoc openapi/astradesk-admin.v1.yaml


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/SSobol77/astradesk
      name: GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/your-handle
      name: Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/your-company
      name: LinkedIn