[project]
name = "astradesk"
version = "0.2.1"
description = "AstraDesk – internal AI agents framework (Python core)"
requires-python = ">=3.11,<3.12"
authors = [{name="Siergej Sobolewski", email="s.sobolewski@hotmail.com"}]
license = {text = "MIT"}

dependencies = [
  "fastapi>=0.115",
  "uvicorn[standard]>=0.30",
  "pydantic>=2.8",
  "asyncpg>=0.29",
  "psycopg[binary]>=3.2",
  "redis>=5.0",
  "nats-py>=2.7",
  "httpx>=0.27",
  "sentence-transformers>=3.0",
  "opentelemetry-sdk>=1.26",
  "opentelemetry-instrumentation-fastapi>=0.47b0",
  "opentelemetry-exporter-otlp>=1.26",
  "tenacity>=9.0",
  "python-json-logger>=2.0",
  "python-jose[cryptography]>=3.3.0",   # JWT
  "jwcrypto>=1.5.6"                      # JWKS fallback
]

[project.optional-dependencies]
dev = ["ruff>=0.5.7","mypy>=1.11","pytest>=8.3","pytest-asyncio>=0.23","httpx>=0.27","types-redis"]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.mypy]
python_version = "3.11"
strict = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
