# SPDX-License-Identifier: GPL-2.0-only
# Project: AstraDesk
# File: deploy/chart/templates/hpa.yaml
# Website: https://www.astradesk.dev
# Repository: https://github.com/SSobol77/astradesk
#
# Description: Configures the associated AstraDesk component or deployment.
#
# Copyright (c) 2026 Siergej Sobolewski
#
# This file is part of AstraDesk.
#
# AstraDesk is licensed under the GNU General Public License version 2 only.
# See the LICENSE file in the project root for the full license text.

{{- range $service := list "api" "ticketAdapter" "admin" "auditor" }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: astradesk-{{ $service | kebabcase }}-hpa
  namespace: {{ $.Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: astradesk-{{ $service | kebabcase }}
  minReplicas: {{ index $.Values $service "autoscaling" "minReplicas" }}
  maxReplicas: {{ index $.Values $service "autoscaling" "maxReplicas" }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ index $.Values $service "autoscaling" "targetCPUUtilizationPercentage" }}
{{- end }}
