# SPDX-License-Identifier: Apache-2.0
# File: packages/domain-supply/flows/exception_routing.yaml
# Description: AstraDSL flow for routing supply chain exceptions.
# Upload via API POST /flows for production integration.

flow: supply_exception_routing
version: 2.1
trigger: { type: webhook, endpoint: "/supply/exceptions" }
steps:
  - id: fetch
    use: tool.sap_mm.fetch_inventory
    with: { query: "SELECT material, stock FROM MM WHERE stock < min_stock" }
  - id: replenish
    use: agent.supply.replenish
    input: ${fetch.items}
  - id: notify
    use: tool.email.send
    input: ${replenish.items}
    params: { to: "supply-team@company.com", subject: "Urgent Replenishment: ${item.item_id}" }
    when: ${item.priority} == "urgent"
policies:
  retry: { max: 3, backoff: "exp_jitter" }
  pii: "redact_auto"
  guardrails: [cost_threshold=0.01]
outputs:
  - type: report
    format: csv
    target: s3://supply-reports/${now}.csv
