# SPDX-License-Identifier: Apache-2.0
# core/pyproject.toml

[project]
name = "astradesk-core"
version = "0.3.0"
description = "Core shared utilities, exceptions, and base models for the AstraDesk Framework."
authors = [{ name = "Siergej Sobolewski", email = "s.sobolewski@hotmail.com" }]
license = { text = "Apache-2.0" }
requires-python = ">=3.14"

# Zależności produkcyjne potrzebne dla `core`.
dependencies = [
    "pydantic>=2.8,<2.9",
    "httpx>=0.27,<0.28", # Potrzebne dla fabryk wyjątków HTTP
]

[project.optional-dependencies]
# Zależności deweloperskie potrzebne do testowania tego pakietu.
dev = [
    "pytest>=8.3",
    "pytest-asyncio>=0.23",
]

# Konfiguracja narzędzi (ruff, mypy, pytest) jest zdefiniowana w głównym
# `pyproject.toml` i jest automatycznie stosowana do tego pakietu
# przez `uv workspace`. Nie trzeba jej tutaj powtarzać.