# SPDX-License-Identifier: GPL-2.0-only
# Project: AstraDesk
# File: deploy/istio/generation-b-reference/certs/astradesk-ca-clusterissuer.yaml
# Website: https://www.astradesk.dev
# Repository: https://github.com/SSobol77/astradesk
#
# Description: Configures the associated AstraDesk component or deployment.
#
# Copyright (c) 2026 Siergej Sobolewski
#
# This file is part of AstraDesk.
#
# AstraDesk is licensed under the GNU General Public License version 2 only.
# See the LICENSE file in the project root for the full license text.

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: astradesk-ca
spec:
  ca:
    secretName: astradesk-ca-secret  # References CA cert/key from astradesk-ca-certificate.yaml
