# SPDX-License-Identifier: GPL-2.0-only
# Project: AstraDesk
# File: packages/domain-finance/proto/finance_pb2_grpc.py
# Website: https://www.astradesk.dev
# Repository: https://github.com/SSobol77/astradesk
#
# Description: Minimal gRPC helper generated by hand for the finance service tests.
# Copyright (c) 2026 Siergej Sobolewski
#
# This file is part of AstraDesk.
#
# AstraDesk is licensed under the GNU General Public License version 2 only.
# See the LICENSE file in the project root for the full license text.

from __future__ import annotations

import json
from typing import Any

import grpc

from domain_finance.proto.finance_pb2 import (
    FetchSalesRequest,
    FetchSalesResponse,
    SalesItem,
)


def _serialize_fetch_sales_request(request: FetchSalesRequest) -> bytes:
    return json.dumps({"query": request.query}, separators=(",", ":")).encode("utf-8")


def _deserialize_fetch_sales_request(payload: bytes) -> FetchSalesRequest:
    return FetchSalesRequest(**json.loads(payload.decode("utf-8")))


def _serialize_fetch_sales_response(response: FetchSalesResponse) -> bytes:
    return json.dumps(
        {
            "items": [
                {"revenue": item.revenue, "date": item.date} for item in response.items
            ]
        },
        separators=(",", ":"),
    ).encode("utf-8")


def _deserialize_fetch_sales_response(payload: bytes) -> FetchSalesResponse:
    data = json.loads(payload.decode("utf-8"))
    return FetchSalesResponse(items=[SalesItem(**item) for item in data["items"]])


class FinanceServiceStub:
    """Client-side stub used by GrpcOracleErpClient."""

    SERVICE_NAME = "FinanceService"

    def __init__(self, channel: grpc.aio.Channel | None = None):
        self._channel = channel

    async def FetchSales(
        self, request, context=None
    ) -> FetchSalesResponse:  # context kept for compatibility
        if self._channel is None:
            raise NotImplementedError(
                "FinanceServiceStub without channel is intended for server subclassing."
            )
        fetch_sales = self._channel.unary_unary(
            f"/{self.SERVICE_NAME}/FetchSales",
            request_serializer=_serialize_fetch_sales_request,
            response_deserializer=_deserialize_fetch_sales_response,
        )
        return await fetch_sales(request)


def add_FinanceServiceServicer_to_server(
    servicer: Any, server: grpc.aio.Server
) -> None:
    """Register an async finance servicer using the public gRPC server API."""
    rpc_method_handlers = {
        "FetchSales": grpc.unary_unary_rpc_method_handler(
            servicer.FetchSales,
            request_deserializer=_deserialize_fetch_sales_request,
            response_serializer=_serialize_fetch_sales_response,
        )
    }
    generic_handler = grpc.method_handlers_generic_handler(
        FinanceServiceStub.SERVICE_NAME,
        rpc_method_handlers,
    )
    server.add_generic_rpc_handlers((generic_handler,))


__all__ = ["FinanceServiceStub", "add_FinanceServiceServicer_to_server"]
