# SPDX-License-Identifier: Apache-2.0
# File:packages/domain-support/pyproject.toml
# Author: Siergej Sobolewski
# Since: 2025-10-26

[project]
name = "astradesk-domain-support"
version = "0.3.0"
description = "Support domain pack for AstraDesk — ticket triage with integrations for JIRA, Slack, and Asana."
authors = [{ name = "Siergej Sobolewski", email = "s.sobolewski@hotmail.com" }]
license = { text = "Apache-2.0" }
requires-python = ">=3.14"

dependencies = [
  # Zależności od innych pakietów w naszym monorepo.
  "astradesk-core",
  # Zależności produkcyjne specyficzne TYLKO dla tej paczki.
  # Na podstawie struktury plików, ta paczka może w przyszłości potrzebować
  # bibliotek do integracji z JIRA, Slack, Asana. Na razie zostawiamy pustą.
  # Przykład: "jira>=3.0"
]

[project.optional-dependencies]
# Zależności deweloperskie specyficzne dla testowania tej paczki.
dev = [
    "pytest>=8.3",
    "pytest-asyncio>=0.23",
    # Do mockowania zapytań HTTP w testach narzędzi
    "respx>=0.20,<1.0", 
]

# Konfiguracja narzędzi (ruff, mypy, pytest) jest zdefiniowana w głównym
# `pyproject.toml` i jest automatycznie stosowana do tego pakietu
# przez `uv workspace`. Nie trzeba jej tutaj powtarzać.