# SPDX-License-Identifier: Apache-2.0
# File: packages/domain-support/pyproject.toml
# Author: Siergej Sobolewski
# Since: 2025-10-27

[project]
name = "astradesk-domain-support"
version = "0.3.0"
description = "Support domain pack for AstraDesk — ticket triage with integrations for JIRA, Slack, and Asana."
authors = [{ name = "Siergej Sobolewski", email = "s.sobolewski@hotmail.com" }]

license = "Apache-2.0"
requires-python = ">=3.14"

dependencies = [
  "astradesk-core",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3",
    "pytest-asyncio>=0.23",
    "respx>=0.20,<1.0", 
]

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["flows*", "agents*", "clients*", "policies*"]
