# SPDX-License-Identifier: Apache-2.0
# File: deploy/istio/10-peer-authentication.yaml
# Description:
#     Configures mandatory mutual TLS (mTLS) for the astradesk namespace.
#     Ensures all traffic between Pods in the namespace uses mutual TLS authentication.
#     Compatible with Istio 1.18+ and cert-manager for certificate management.
#     Applies to workloads like domain-support, domain-finance, domain-supply, and ticket-adapter-java.
# Author: Siergej Sobolewski
# Since: 2025-10-22

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: astradesk-peer-auth
  namespace: astradesk
spec:
  mtls:
    mode: STRICT  # Enforces mutual TLS for all traffic in the namespace
  selector:  # Optional: Restrict mTLS to specific workloads (uncomment if needed)
    matchLabels:
      app: astradesk  # Matches Pods with label app=astradesk (e.g., domain-support, ticket-adapter-java)
