# SPDX-License-Identifier: Apache-2.0
# File: deploy/istio/30-authorizationpolicy-namespace.yaml
# Description:
#     Defines an AuthorizationPolicy to restrict traffic in the astradesk namespace.
#     Allows traffic only from within the namespace or from Istio IngressGateway.
#     Compatible with Istio STRICT mTLS (10-peer-authentication.yaml) and Gateway (40-gateway.yaml).
# Author: Siergej Sobolewski
# Since: 2025-10-22

apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: astradesk-allow-from-namespace-and-ingress
  namespace: astradesk
spec:
  selector:
    matchLabels:
      app: astradesk  # Applies to workloads with label app=astradesk (e.g., astradesk-api)
  rules:
    - from:
        - source:
            namespaces: ["astradesk"]  # Allows traffic from within astradesk namespace
      to:
        - operation: {}  # All operations from internal services
    - from:
        - source:
            principals:
              - "cluster.local/ns/istio-system/sa/istio-ingressgateway-service-account"  # Istio IngressGateway SA
      to:
        - operation: {}  # All operations from IngressGateway
