# SPDX-License-Identifier: GPL-2.0-only
# Project: AstraDesk
# File: deploy/istio/certmanager.yaml
# Website: https://www.astradesk.dev
# Repository: https://github.com/SSobol77/astradesk
#
# Description: Configures the associated AstraDesk component or deployment.
#
# Copyright (c) 2026 Siergej Sobolewski
#
# This file is part of AstraDesk.
#
# AstraDesk is licensed under the GNU General Public License version 2 only.
# See the LICENSE file in the project root for the full license text.

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: astradesk-selfsigned-issuer
  namespace: astradesk-prod
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: astradesk-tls
  namespace: astradesk-prod
spec:
  secretName: astradesk-tls
  issuerRef:
    name: astradesk-selfsigned-issuer
    kind: Issuer
  commonName: astradesk.local
  dnsNames:
  - "*.astradesk.local"
  - "api.astradesk.local"
  - "ticket.astradesk.local"
  - "admin.astradesk.local"
  - "auditor.astradesk.local"
