name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
      - run: npm install
        working-directory: services/admin-portal
      - run: npm run lint
        working-directory: services/admin-portal
      - run: npm run typecheck
        working-directory: services/admin-portal
      - run: npm run openapi:check
        working-directory: services/admin-portal
      - run: npm run build
        working-directory: services/admin-portal
      - run: npm run test
        working-directory: services/admin-portal
