name: Deploy Docs to GitHub Pages (uv)

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - ".github/workflows/gh-pages.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true

      - name: Install Python (via uv)
        run: uv python install 3.11

      - name: Build site (MkDocs via uv)
        run: |
          uv venv
          uv pip install mkdocs mkdocs-material pymdown-extensions
          # uv pip install mkdocs-mermaid2-plugin
          uv run mkdocs build --strict

      - name: Copy OpenAPI to docs
        run: |
          mkdir -p docs/api
          cp openapi/astradesk-admin.v1.yaml docs/api/openapi.yaml

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
